# Generated by Django 4.2.1 on 2023-06-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileMixin',
        ),
    ]
