version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/cloud-tech-webapp/
permissions:
  - object: /home/ubuntu/cloud-tech-webapp/
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1200
      runas: root
  AfterInstall:
    - location: scripts/build_run.sh
      timeout: 600
      runas: root
