version: 0.0
os: linux
files:
  - source: /
    destination: /root/cloud-tech-webapp/
permissions:
  - object: /root/cloud-tech-webapp/
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - inline:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 851725593378.dkr.ecr.ap-south-1.amazonaws.com 
      - docker pull 851725593378.dkr.ecr.ap-south-1.amazonaws.com/cloudtech:latest
      timeout: 1200
      runas: root
  AfterInstall:
    - inline:
      - cd cloud-tech-webapp
      - git pull
      - ls -a
      - docker-compose down
      - docker-compose up -d
      timeout: 600
      runas: root
