version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 392488130328.dkr.ecr.ap-south-1.amazonaws.com/cloudtech
  build:
    commands:
      - echo Building the Docker image...
      - sudo docker build -t 392488130328.dkr.ecr.ap-south-1.amazonaws.com/cloudtech/webapp:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - sudo docker push 392488130328.dkr.ecr.ap-south-1.amazonaws.com/cloudtech/webapp:latest
