version: 0.2

phases:
  install:
    commands:
      - pip3 install -q awscli --upgrade --user
  pre_build:
    commands:
      - aws --version
      - aws s3 ls
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 851725593378.dkr.ecr.ap-south-1.amazonaws.com
      - if docker image inspect 851725593378.dkr.ecr.ap-south-1.amazonaws.com/cloudtech:latest > /dev/null 2>&1; then
          echo "Image exists. Removing...";
          docker rmi 851725593378.dkr.ecr.ap-south-1.amazonaws.com/cloudtech:latest;
        else
          echo "Image does not exist. Skipping removal.";
        fi
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t cloudtech .
  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag cloudtech:latest 851725593378.dkr.ecr.ap-south-1.amazonaws.com/cloudtech:latest
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 851725593378.dkr.ecr.ap-south-1.amazonaws.com/cloudtech:latest

artifacts:
  files:
    - '**/*'
