version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  django-app:
    env_file:
      - cloudtech_project/.env
    image: 851725593378.dkr.ecr.ap-south-1.amazonaws.com/cloudtech:latest
    ports:
      - 8000:8000
    command:
      - python manage.py collectstatic --noinput
      - python manage.py makemigrations
      - python manage.py migrate
      - uwsgi --http :8000 --master --enable-threads --module cloudtech_project.wsgi

  celery-worker:
    env_file:
      - cloudtech_project/.env
    image: 851725593378.dkr.ecr.ap-south-1.amazonaws.com/cloudtech:latest
    command: 
      - celery -A cloudtech_project worker -l info
    depends_on:
      - redis
