version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  django-app:
    image: 392488130328.dkr.ecr.ap-south-1.amazonaws.com/cloudtech:latest
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

  celery-worker:
    image: 392488130328.dkr.ecr.ap-south-1.amazonaws.com/cloudtech:latest
    command: celery -A cloudtech_project worker -l info
    depends_on:
      - redis

