[tool.poetry]
name = "cloud-tech-webapp"
version = "0.1.0"
description = ""
authors = ["ishan-modi <ishan.modi@glib.ai>"]
readme = "README.md"
packages = [{include = "cloud_tech_webapp"}]

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
