# Generated by Django 4.2.1 on 2023-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='add_blog',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='community',
            name='add_discussion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='add_project',
            field=models.BooleanField(default=False),
        ),
    ]
