# Generated by Django 4.2.1 on 2023-06-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemixin',
            name='profile_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
