# Generated by Django 4.2.1 on 2023-06-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profilemixin_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemixin',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
