# Generated by Django 4.2.1 on 2023-06-20 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='co_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='community.tag'),
        ),
        migrations.AlterField(
            model_name='monthly',
            name='tags',
            field=models.ManyToManyField(to='community.tag'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='co_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(to='community.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='community.tag'),
        ),
    ]
