# Generated by Django 4.2.1 on 2023-06-14 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='md_file',
            field=models.FileField(default='/home/ishan/Downloads/Top 5 Announcements from AWS re_Invent 2021 for Data and DevOps .md', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md'])]),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='md_file',
            field=models.FileField(default='/home/ishan/Downloads/Top 5 Announcements from AWS re_Invent 2021 for Data and DevOps .md', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md'])]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='co_author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='monthly',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='co_author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
