# Generated by Django 4.2.1 on 2023-06-14 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_blog_md_file_newsletter_md_file_alter_blog_co_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='md_file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md'])]),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='md_file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md'])]),
        ),
    ]
