# Generated by Django 4.2.1 on 2023-06-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_blog_md_file_alter_newsletter_md_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='md_file',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='md_file',
        ),
    ]
