# Generated by Django 4.2.1 on 2023-06-16 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_community_add_newsletter'),
        ('content', '0005_remove_blog_author_remove_newsletter_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='co_author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='community.tag'),
        ),
        migrations.AlterField(
            model_name='monthly',
            name='tags',
            field=models.ManyToManyField(blank=True, to='community.tag'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='co_author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(blank=True, to='community.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='community.tag'),
        ),
    ]
